repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-simplify',
            'flake8-import-order',
            'flake8-quotes',
            'flake8-print',
            'flake8-debugger',
            'flake8-eradicate',
            'flake8-mutable',
            'flake8-multiline-containers',
            'flake8-pytest-style',
            'flake8-requirements',
            'flake8-string-format',
            'flake8-tidy-imports',
            'flake8-variables-names',
            'pep8-naming',
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-requests',
            'types-python-dateutil',
            'types-PyYAML',
            'types-setuptools',
            'types-urllib3',
            'types-pytz',
            'types-six',
            'types-toml',
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/PyCQA/pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
        args: [
            "--rcfile=pyproject.toml",
            "--disable=C0111",  # missing-docstring
        ]

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args: ["--config=pyproject.toml"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: ["--py38-plus"]

-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
    -   id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies: [
            'eslint',
            'eslint-config-prettier',
            'eslint-plugin-prettier',
            'eslint-plugin-react',
            'eslint-plugin-react-hooks',
            '@typescript-eslint/eslint-plugin',
            '@typescript-eslint/parser',
        ]

-   repo: https://github.com/pre-commit/mirrors-stylelint
    rev: v15.11.0
    hooks:
    -   id: stylelint
        files: \.(css|scss)$
        types: [file]
        additional_dependencies: [
            'stylelint',
            'stylelint-config-standard',
            'stylelint-config-prettier',
        ] 