# Trading Bot Configuratie

# Exchange Configuration
exchange:
  name: "bybit"
  testnet: true
  api:
    key: ${BYBIT_API_KEY}
    secret: ${BYBIT_API_SECRET}
    base_url: "https://api.bybit.com/v5"
    endpoints:
      tickers: "/market/tickers"
      candles: "/market/kline"
      trades: "/trade"
    timeout: 10
    max_retries: 3
    retry_delay: 5
    rate_limit:
      calls_per_second: 2
      calls_per_minute: 50
      calls_per_hour: 1000

# Backtest Settings
backtest:
  initial_capital: 10000.0
  commission_rate: 0.001
  slippage_rate: 0.0005
  start_date: "2024-01-01"
  end_date: "2024-07-17"

# Trading Parameters
trading:
  min_volume: 2000000  # Verhoogd voor betere liquiditeit
  volume_ma_period: 20
  min_atr: 1.0  # Verhoogd voor betere volatiliteit filter
  atr_period: 14
  max_spread: 0.1  # Verlaagd voor betere uitvoering
  min_margin: 0.1
  max_margin: 0.3  # Verlaagd voor minder risico
  min_risk_reward: 3.0  # Verhoogd voor betere risk/reward
  max_open_trades: 3  # Verlaagd voor minder risico
  max_daily_trades: 10  # Verlaagd voor betere kwaliteit
  max_daily_loss: 2.0  # Verlaagd voor betere risicobeheersing
  symbols:
    BTCUSDT:
      min_volume: 1000000
      min_volatility: 0.001
      max_spread: 0.001
      leverage: 1
      enabled: true
      max_position_size: null
      min_position_size: null
    ETHUSDT:
      min_volume: 500000
      min_volatility: 0.001
      max_spread: 0.001
      leverage: 1
      enabled: true
      max_position_size: null
      min_position_size: null

# Strategy Parameters
strategy:
  indicators:
    rsi:
      period: 14
      overbought: 75  # Aangepast voor minder valse signalen
      oversold: 25
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger_bands:
      period: 20
      std_dev: 2.5  # Verhoogd voor minder valse signalen
    ema:
      short_period: 9
      medium_period: 21
      long_period: 50
    volume_ma:
      period: 20
    atr:
      period: 14
    adx:
      period: 14
      threshold: 25
    stochastic_rsi:
      rsi_period: 14
      stochastic_period: 14
      k_period: 3
      d_period: 3
      overbought: 80
      oversold: 20
    obv:
      smoothing: 5
  exit:
    max_trade_duration: 12  # Verlaagd voor snellere exits
    trailing_stop:
      enabled: true
      activation: 0.015  # Verhoogd voor betere winstbescherming
      step: 0.005
    take_profit:
      enabled: true
      levels: [0.02, 0.03, 0.04]
      portions: [0.4, 0.3, 0.3]  # Aangepast voor betere winstbescherming
    stop_loss:
      enabled: true
      initial: 0.015  # Verlaagd voor betere risicobeheersing
      breakeven: 0.01
  market_regime:
    trend:
      min_trend_period: 20
      trend_threshold: 0.02
      confirmation_periods: 3
      position_multiplier: 1.2
      stop_loss_multiplier: 1.0
      take_profit_multiplier: 1.0
    volatility:
      low_volatility: 0.01
      medium_volatility: 0.025
      high_volatility: 0.04
      position_multiplier: 0.8
      stop_loss_multiplier: 1.0
      take_profit_multiplier: 1.0
    volume:
      low_volume: 1500000
      medium_volume: 4000000
      high_volume: 20000000
      position_multiplier: 0.6
      stop_loss_multiplier: 1.5
      take_profit_multiplier: 2.0

# Timeframes
timeframes:
  - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d
  update_interval: 1
  polling_interval: 1
  report_interval: 3600

# Risk Management
risk:
  position_sizing:
    max_position_size: 0.02
    base_risk_per_trade: 0.005
    max_correlation: 0.7
    max_open_positions: 3
    max_daily_loss: 0.02
    max_drawdown: 0.1
    trailing_stop:
      enabled: true
      activation: 0.02
      distance: 0.01
  portfolio:
    max_leverage: 1.0
  limits:
    max_daily_loss: 0.02
    max_weekly_loss: 0.05
    max_monthly_loss: 0.08
    min_win_rate: 0.45
  stop_loss:
    type: fixed
    value: 0.015  # 1.5%
  take_profit:
    type: fixed
    value: 0.03  # 3%
  trailing_stop:
    enabled: true
    activation: 0.01  # 1%
    distance: 0.005  # 0.5%

# Performance Tracking
performance:
  enabled: true
  metrics:
    - win_rate
    - profit_factor
    - sharpe_ratio
    - max_drawdown
    - average_win
    - average_loss
  report_interval: 86400  # 24 uur
  save_reports: true
  report_dir: "reports"

# Telegram
telegram:
  enabled: true
  token: ${TELEGRAM_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}
  max_retries: 3
  retry_delay: 5
  rate_limit: 30  # berichten per minuut
  alert_types:
    - TRADE
    - ERROR
    - SYSTEM
    - WARNING

# Logging
logging:
  log_dir: "logs"
  log_level: "INFO"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file_logging: true
  max_file_size: 10485760  # 10MB
  backup_count: 5
  console_logging: true
  json_logging: true
  performance_logging: true
  monitoring:
    save_trades: true
    save_equity_curve: true
    save_drawdown: true
    alert_thresholds:
      drawdown: 0.1
      daily_loss: 0.03
      weekly_loss: 0.06
      monthly_loss: 0.12

# Cache
cache:
  enabled: true
  ttl: 300  # 5 minuten
  max_size: 1000
  cleanup_interval: 3600  # 1 uur

# Database
database:
  url: "sqlite:///trading_bot.db"
  pool_size: 5
  max_overflow: 10
  echo: false
  pool_recycle: 3600
  pool_timeout: 30

# Monitoring
monitoring:
  enabled: true
  interval: 60  # seconden
  metrics:
    - cpu_usage
    - memory_usage
    - disk_usage
    - network_usage
    - trade_performance
  alerts:
    - high_cpu
    - high_memory
    - error_rate
    - trade_failure

# Backup
backup:
  enabled: true
  interval: 86400  # 24 uur
  keep_backups: 7
  backup_dir: "backups"
  compress: true

# Trading Schedule
schedule:
  trading_hours:
    start: "00:00"
    end: "23:59"
  trading_days:
    - "Monday"
    - "Tuesday"
    - "Wednesday"
    - "Thursday"
    - "Friday"
    - "Saturday"
    - "Sunday"
  market_events:
    avoid_news: true
    avoid_high_impact: true
    avoid_volatility: false

# Optimization Parameters
optimization:
  ranges:
    rsi_period: [10, 18]
    macd_fast: [10, 14]
    macd_slow: [24, 30]
    bollinger_period: [18, 25]
    bollinger_std: [1.8, 2.4]
  method: "genetic"
  population_size: 100
  generations: 50
  mutation_rate: 0.08
  crossover_rate: 0.9

# Advanced Features
advanced:
  ml:
    enabled: false
    model_type: "xgboost"
    features:
      - "technical_indicators"
      - "market_regime"
      - "volume_profile"
    training_period: 365
    retrain_frequency: 30
  market_making:
    enabled: false
    spread_multiplier: 1.5
    inventory_target: 0.0
    max_inventory: 1.0
  arbitrage:
    enabled: false
    min_profit: 0.001
    max_slippage: 0.0005
    max_trade_size: 1.0

api:
  key: ${BYBIT_API_KEY}
  secret: ${BYBIT_API_SECRET}
  base_url: "https://api.bybit.com/v5"
  timeout: 10
  max_retries: 3
  retry_delay: 5
  rate_limit:
    calls_per_second: 2
    calls_per_minute: 50
    calls_per_hour: 1000