# Trading Bot Configuratie

# Exchange Configuration
exchange:
  name: "bybit"
  testnet: true
  api:
    base_url: "https://api-testnet.bybit.com"
    api_key: ""
    api_secret: ""
    timeout: 10
    max_retries: 3
    retry_delay: 5
    rate_limit:
      calls: 2
      period: 1

# Backtest Settings
backtest:
  initial_capital: 10000
  start_date: "2024-01-01"
  end_date: "2024-02-01"
  symbols:
    - "BTCUSDT"
  timeframes:
    - "1m"
    - "5m"
    - "1h"
  commission: 0.001
  slippage: 0.001
  risk_free_rate: 0.02

# Trading Parameters
trading:
  cycle_interval: 1  # seconds
  timeframes:
    - "1m"
    - "5m"
    - "1h"
  min_volume: 1000000
  volume_ma_period: 20
  min_atr: 0.5
  atr_period: 14
  max_spread: 0.001
  min_margin: 0.1
  max_margin: 0.9
  min_risk_reward: 2.0
  max_open_trades: 3
  max_daily_trades: 10
  max_daily_loss: 0.02
  symbols:
    BTCUSDT:
      min_volume: 1000000
      min_volatility: 0.001
      max_spread: 0.001
      leverage: 1
      enabled: true
      max_position_size: null
      min_position_size: null
    ETHUSDT:
      min_volume: 500000
      min_volatility: 0.001
      max_spread: 0.001
      leverage: 1
      enabled: true
      max_position_size: null
      min_position_size: null
  update_interval: 1
  polling_interval: 1
  report_interval: 3600
  timeframe: "1h"
  strategy: "trend_following"

# Strategy Parameters
strategy:
  indicators:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger:
      period: 20
      std_dev: 2.0
    ema:
      short_period: 9
      medium_period: 21
      long_period: 50
    volume_ma:
      period: 20
    adx:
      period: 14
      threshold: 20
  market_regime:
    min_confidence: 0.6
    lookback_period: 100
  signal:
    min_signals: 3
    min_strength: 0.6
    min_volume_multiplier: 1.5
    min_atr_multiplier: 1.2

# Trading Symbols met specifieke parameters
symbols:
  BTCUSDT:
    min_volume: 1000000
    min_atr: 0.5
    max_spread: 0.002
    min_margin: 0.1
    max_margin: 0.9

  ETHUSDT:
    min_volume: 500000
    min_atr: 0.3
    max_spread: 0.003
    min_margin: 0.1
    max_margin: 0.9

  BNBUSDT:
    min_volume: 10000000
    volume_ma_period: 20
    min_atr: 0.5
    atr_period: 14
    max_spread: 0.003
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  SOLUSDT:
    min_volume: 5000000
    volume_ma_period: 20
    min_atr: 0.1
    atr_period: 14
    max_spread: 0.004
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  XRPUSDT:
    min_volume: 3000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  ADAUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  DOTUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.01
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  LINKUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.01
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  MATICUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  AVAXUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.1
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  DOGEUSDT:
    min_volume: 1000000
    volume_ma_period: 20
    min_atr: 0.0001
    atr_period: 14
    max_spread: 0.01
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  SHIBUSDT:
    min_volume: 1000000
    volume_ma_period: 20
    min_atr: 0.0000001
    atr_period: 14
    max_spread: 0.01
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

# Timeframes
timeframes:
  - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d

# Risk Management
risk:
  max_position_size: 0.03
  max_daily_trades: 10
  max_daily_loss: 0.02
  max_drawdown: 0.15
  min_risk_reward: 2.0
  max_open_trades: 3
  base_risk_per_trade: 0.01
  stop_loss:
    type: fixed
    value: 0.015
  take_profit:
    type: fixed
    value: 0.03
  trailing_stop:
    enabled: true
    activation: 0.01
    distance: 0.005
  max_trade_duration: 24  # hours

# Performance Tracking
performance:
  enabled: true
  metrics:
    - win_rate
    - profit_factor
    - sharpe_ratio
    - max_drawdown
    - average_win
    - average_loss
  report_interval: 86400  # 24 uur
  save_reports: true
  report_dir: "reports"

# Telegram
telegram:
  enabled: false
  bot_token: "YOUR_BOT_TOKEN"
  chat_id: "YOUR_CHAT_ID"
  max_retries: 3
  retry_delay: 1
  rate_limit: 30  # messages per minute

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file:
    enabled: true
    path: "logs/trading_bot.log"
    max_size: 10485760  # 10MB
    backup_count: 5
  console:
    enabled: true

# Cache
cache:
  enabled: true
  ttl: 300  # 5 minuten
  max_size: 1000
  cleanup_interval: 3600  # 1 uur

# Database
database:
  url: "sqlite:///trading_bot.db"
  pool_size: 5
  max_overflow: 10
  echo: false
  pool_recycle: 3600
  pool_timeout: 30

# Monitoring
monitoring:
  enabled: true
  interval: 60  # seconden
  metrics:
    - cpu_usage
    - memory_usage
    - disk_usage
    - network_usage
    - trade_performance
  alerts:
    - high_cpu
    - high_memory
    - error_rate
    - trade_failure
  check_interval: 300  # 5 minutes
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 80
    disk_usage: 80
    error_rate: 5

# Backup
backup:
  enabled: true
  interval: 86400  # 24 uur
  keep_backups: 7
  backup_dir: "backups"
  compress: true

# Trading Schedule
schedule:
  trading_hours:
    start: "00:00"
    end: "23:59"
  trading_days:
    - "Monday"
    - "Tuesday"
    - "Wednesday"
    - "Thursday"
    - "Friday"
    - "Saturday"
    - "Sunday"
  market_events:
    avoid_news: true
    avoid_high_impact: true
    avoid_volatility: false

# Optimization Parameters
optimization:
  ranges:
    rsi_period: [10, 18]
    macd_fast: [10, 14]
    macd_slow: [24, 30]
    bollinger_period: [18, 25]
    bollinger_std: [1.8, 2.4]
  method: "genetic"
  population_size: 100
  generations: 50
  mutation_rate: 0.08
  crossover_rate: 0.9

# Advanced Features
advanced:
  ml:
    enabled: false
    model_type: "xgboost"
    features:
      - "technical_indicators"
      - "market_regime"
      - "volume_profile"
    training_period: 365
    retrain_frequency: 30
  market_making:
    enabled: false
    spread_multiplier: 1.5
    inventory_target: 0.0
    max_inventory: 1.0
  arbitrage:
    enabled: false
    min_profit: 0.001
    max_slippage: 0.0005
    max_trade_size: 1.0

api:
  key: ${BYBIT_API_KEY}
  secret: ${BYBIT_API_SECRET}
  base_url: "https://api.bybit.com/v5"
  timeout: 10
  max_retries: 3
  retry_delay: 5
  rate_limit:
    calls_per_second: 2
    calls_per_minute: 50
    calls_per_hour: 1000