# Trading Bot Configuration

# OpenAI Configuration
openai:
  api_key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL}
  temperature: ${OPENAI_TEMPERATURE}
  max_tokens: ${OPENAI_MAX_TOKENS}
  presence_penalty: 0.1
  frequency_penalty: 0.1

# Exchange Configuration
exchange:
  name: ${EXCHANGE_NAME}
  testnet: ${EXCHANGE_TESTNET}
  api:
    key: ${BYBIT_API_KEY}
    secret: ${BYBIT_API_SECRET}
    base_url: ${EXCHANGE_BASE_URL}
    endpoints:
      tickers: "/market/tickers"
      candles: "/market/kline"
      trades: "/trade"
    timeout: 10
    max_retries: 3
    retry_delay: 5
    rate_limit:
      calls_per_second: 2
      calls_per_minute: 50
      calls_per_hour: 1000

# Backtest Settings
backtest:
  initial_capital: 10000.0
  commission_rate: 0.001
  slippage_rate: 0.0005
  start_date: "2019-01-01"
  end_date: "2024-01-01"
  timeframes:
    - 1m
    - 5m
    - 1h
    - 4h
  data_dir: "data/historical"

# Trading Parameters
trading:
  cycle_interval: 60
  timeframes: ['1m', '5m', '15m', '1h']
  min_volume: 100000
  volume_ma_period: 20
  min_atr: 0.1
  atr_period: 14
  max_spread: 0.002
  min_margin: 0.05
  max_margin: 0.95
  min_risk_reward: 1.5
  max_open_trades: 5
  max_daily_trades: 20
  max_daily_loss: 0.35
  symbols:
    BTCUSDT:
      min_volume: 1000000
      min_volatility: 0.0005
      max_spread: 0.002
      leverage: 1
      enabled: true
  timeframe: "1h"
  strategy:
    name: "ai_strategy"
    parameters:
      min_confidence: 0.6
      max_position_size: 0.05

# Strategy Parameters
strategy:
  indicators:
    rsi:
      period: 14
      overbought: 70
      oversold: 30
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
    bollinger_bands:
      period: 20
      std_dev: 2.0
    ema:
      short_period: 9
      medium_period: 21
      long_period: 50
    volume_ma:
      period: 20
    atr:
      period: 14
    adx:
      period: 14
      threshold: 25
    stochastic_rsi:
      rsi_period: 14
      stochastic_period: 14
      k_period: 3
      d_period: 3
    obv:
      smoothing: 5
  market_regime:
    min_confidence: 0.6
    lookback_period: 100
  signal:
    min_signals: 3
    min_strength: 0.6
    min_volume_multiplier: 1.5
    min_atr_multiplier: 1.2

# Risk Management
risk:
  max_position_size: 0.05
  max_daily_trades: 20
  max_daily_loss: 0.35
  max_drawdown: 0.35
  min_risk_reward: 1.5
  max_open_trades: 5
  base_risk_per_trade: 0.02
  stop_loss:
    type: fixed
    value: 0.02
  take_profit:
    type: fixed
    value: 0.03
  trailing_stop:
    enabled: true
    activation: 0.015
    distance: 0.005
  max_trade_duration: 48

# Trading Symbols met specifieke parameters
symbols:
  BTCUSDT:
    min_volume: 50000000
    volume_ma_period: 20
    min_atr: 100
    atr_period: 14
    max_spread: 0.001
    min_margin: 0.05
    max_margin: 0.15  # Verlaagd voor minder risico
    min_risk_reward: 3.0  # Verhoogd voor betere risk/reward
    position_size: 0.01  # Verlaagd voor minder risico
    stop_loss: 0.01  # Verlaagd voor betere risicobeheersing
    take_profit: 0.03
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  ETHUSDT:
    min_volume: 20000000
    volume_ma_period: 20
    min_atr: 5
    atr_period: 14
    max_spread: 0.002
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  BNBUSDT:
    min_volume: 10000000
    volume_ma_period: 20
    min_atr: 0.5
    atr_period: 14
    max_spread: 0.003
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  SOLUSDT:
    min_volume: 5000000
    volume_ma_period: 20
    min_atr: 0.1
    atr_period: 14
    max_spread: 0.004
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  XRPUSDT:
    min_volume: 3000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  ADAUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  DOTUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.01
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  LINKUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.01
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  MATICUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.001
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  AVAXUSDT:
    min_volume: 2000000
    volume_ma_period: 20
    min_atr: 0.1
    atr_period: 14
    max_spread: 0.005
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  DOGEUSDT:
    min_volume: 1000000
    volume_ma_period: 20
    min_atr: 0.0001
    atr_period: 14
    max_spread: 0.01
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

  SHIBUSDT:
    min_volume: 1000000
    volume_ma_period: 20
    min_atr: 0.0000001
    atr_period: 14
    max_spread: 0.01
    min_margin: 0.05
    max_margin: 0.2
    min_risk_reward: 2.0
    position_size: 0.1
    stop_loss: 0.02
    take_profit: 0.04
    trailing_stop: true
    trailing_stop_activation: 0.015
    trailing_stop_distance: 0.005

# Timeframes
timeframes:
  - 1m
  - 5m
  - 15m
  - 1h
  - 4h
  - 1d

# Performance Tracking
performance:
  enabled: true
  metrics:
    - win_rate
    - profit_factor
    - sharpe_ratio
    - max_drawdown
    - average_win
    - average_loss
  report_interval: 86400
  save_reports: true
  report_dir: "reports"

# Telegram
telegram:
  enabled: true
  token: ${TELEGRAM_BOT_TOKEN}
  chat_id: ${TELEGRAM_CHAT_ID}
  max_retries: 3
  retry_delay: 5
  rate_limit: 30  # berichten per minuut
  alert_types:
    - TRADE
    - ERROR
    - SYSTEM
    - WARNING

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file:
    enabled: true
    path: "logs/trading_bot.log"
    max_size: 10485760
    backup_count: 5
  console:
    enabled: true

# Cache
cache:
  enabled: true
  ttl: 300
  max_size: 1000
  cleanup_interval: 3600

# Database
database:
  url: "sqlite:///trading_bot.db"
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  pool_size: 5
  max_overflow: 10
  echo: false
  pool_recycle: 3600
  pool_timeout: 30

# Monitoring
monitoring:
  enabled: true
  check_interval: 60  # seconden
  interval: 60  # seconden
  metrics:
    - cpu_usage
    - memory_usage
    - disk_usage
    - network_usage
    - trade_performance
  alerts:
    - high_cpu
    - high_memory
    - error_rate
    - trade_failure
  alert_thresholds:
    cpu_usage: 90
    memory_usage: 90
    disk_usage: 90
    error_rate: 5
    trade_failure: 1

# Backup
backup:
  enabled: true
  interval: 86400  # 24 uur
  keep_backups: 7
  backup_dir: "backups"
  compress: true

# Trading Schedule
schedule:
  trading_hours:
    start: "00:00"
    end: "23:59"
  trading_days:
    - "Monday"
    - "Tuesday"
    - "Wednesday"
    - "Thursday"
    - "Friday"
    - "Saturday"
    - "Sunday"
  market_events:
    avoid_news: true
    avoid_high_impact: true
    avoid_volatility: false

# Optimization Parameters
optimization:
  ranges:
    rsi_period: [10, 18]
    macd_fast: [10, 14]
    macd_slow: [24, 30]
    bollinger_period: [18, 25]
    bollinger_std: [1.8, 2.4]
  method: "genetic"
  population_size: 100
  generations: 50
  mutation_rate: 0.08
  crossover_rate: 0.9

# Advanced Features
advanced:
  ml:
    enabled: false
    model_type: "xgboost"
    features:
      - "technical_indicators"
      - "market_regime"
      - "volume_profile"
    training_period: 365
    retrain_frequency: 30
  market_making:
    enabled: false
    spread_multiplier: 1.5
    inventory_target: 0.0
    max_inventory: 1.0
  arbitrage:
    enabled: false
    min_profit: 0.001
    max_slippage: 0.0005
    max_trade_size: 1.0

# AI Configuration
ai:
  # General settings
  model_dir: 'models'
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  validation_split: 0.2
  
  # Feature engineering
  feature_engineering:
    max_features: 100
    feature_selection_method: 'f_classif'
    preprocessing:
      handle_missing: true
      remove_outliers: true
      normalize: true
    technical_indicators:
      enabled: true
      indicators:
        - 'sma'
        - 'ema'
        - 'rsi'
        - 'macd'
        - 'bollinger_bands'
    feature_selection:
      method: 'f_classif'
      n_features: 10
    dimensionality_reduction:
      method: 'pca'
      n_components: 0.95
  
  # Model pipeline
  model_pipeline:
    validation_split: 0.2
    early_stopping_patience: 10
    model_configs:
      neural_network:
        type: 'neural_network'
        hidden_units: 64
        hidden_layers: 2
        activation: 'relu'
        dropout_rate: 0.2
        optimizer: 'adam'
        loss: 'binary_crossentropy'
      random_forest:
        type: 'random_forest'
        params:
          n_estimators: 100
          max_depth: 10
          min_samples_split: 2
      gradient_boosting:
        type: 'gradient_boosting'
        params:
          n_estimators: 100
          learning_rate: 0.1
          max_depth: 3
  
  # Online learning
  online_learning:
    model_type: 'sgd'
    learning_rate: 0.01
    batch_size: 32
    update_frequency: 1000
    min_samples: 100
    metrics_window: 1000
  
  # Deep learning
  deep_learning:
    cnn:
      blocks: 3
      filters: [32, 64, 128]
      kernel_size: 3
      dropout_rate: 0.25
    rnn:
      layers: 2
      units: [128, 64, 32]
      dropout_rate: 0.3
    transformer:
      num_heads: 8
      key_dim: 64
      ff_dim: 512
      dropout_rate: 0.3
    transfer_learning:
      base_models:
        - 'resnet50'
        - 'vgg16'
        - 'efficientnet'
      fine_tune_layers: 0
  
  # Performance monitoring
  performance:
    monitor_system: true
    monitor_functions: true
    max_metrics_age_days: 7
    max_metrics_count: 1000
    metrics_export_path: 'metrics'
  
  # Security
  security:
    token_expiry_hours: 24
    max_login_attempts: 5
    lockout_duration_minutes: 30
    encryption_key_length: 32
  
  # Event management
  events:
    max_events: 1000
    max_event_age_days: 7
    event_export_path: 'events'
  
  # Error management
  errors:
    max_errors: 1000
    max_error_age_days: 7
    error_export_path: 'errors'
    error_notification: true

# Distributed Computing Configuration
distributed:
  # Cluster settings
  cluster:
    role: 'master'  # 'master' of 'worker'
    master_url: 'http://localhost:8000'
    worker_urls:
      - 'http://localhost:8001'
      - 'http://localhost:8002'
    max_workers: 4
    task_timeout: 300
    heartbeat_interval: 30
  
  # Task management
  task_manager:
    max_workers: 4
    task_timeout: 300
    retry_attempts: 3
    retry_delay: 5
  
  # Load balancing
  load_balancer:
    strategy: 'weighted_random'  # 'round_robin', 'least_loaded', 'weighted_random'
    health_check_interval: 30
    max_retries: 3
    retry_delay: 5
  
  # Performance monitoring
  performance:
    monitor_nodes: true
    monitor_tasks: true
    max_metrics_age_days: 7
    max_metrics_count: 1000
    metrics_export_path: 'metrics'
  
  # Security
  security:
    node_authentication: true
    ssl_enabled: true
    ssl_cert_path: 'certs/server.crt'
    ssl_key_path: 'certs/server.key'
    max_connections: 100
  
  # Event management
  events:
    max_events: 1000
    max_event_age_days: 7
    event_export_path: 'events'
  
  # Error management
  errors:
    max_errors: 1000
    max_error_age_days: 7
    error_export_path: 'errors'
    error_notification: true