name: Update Changelog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitchangelog
    - name: Update changelog
      run: |
        gitchangelog > CHANGELOG.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update changelog
        title: Update changelog
        body: |
          Automated changelog update
        branch: update-changelog
        base: main 