name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    - name: Update requirements
      run: |
        pip-compile --upgrade requirements.in -o requirements.txt
        pip-compile --upgrade requirements-dev.in -o requirements-dev.txt
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update dependencies
        title: Update dependencies
        body: |
          Automated dependency updates:
          - Updated requirements.txt
          - Updated requirements-dev.txt
        branch: update-dependencies
        base: main 